
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firat
 */
public class SiparidUyg extends javax.swing.JFrame {

    
     Map<String,Integer> siparisler=new LinkedHashMap<String,Integer>();//EKLENME SIRASINA GÖRE KAYIT ETMEK İSTERSEM LİNKEDHASHMAP KULLANIRIM
    /**
     * Creates new form SiparidUyg
     */
    public SiparidUyg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        Beyti = new javax.swing.JCheckBox();
        Döner = new javax.swing.JCheckBox();
        Ayran = new javax.swing.JCheckBox();
        göster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siparis Uygulaması");

        jLabel1.setText("            MENU");

        iskender.setText("İskender-15 TL");

        Beyti.setText("Beyti-20 TL");

        Döner.setText("Döner-12 TL");

        Ayran.setText("Ayran-3 TL");

        göster.setText("Siparisleri Göster");
        göster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gösterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iskender, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Beyti)
                        .addComponent(Döner)
                        .addComponent(Ayran))
                    .addComponent(göster, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(iskender)
                .addGap(18, 18, 18)
                .addComponent(Beyti)
                .addGap(18, 18, 18)
                .addComponent(Döner)
                .addGap(18, 18, 18)
                .addComponent(Ayran)
                .addGap(18, 18, 18)
                .addComponent(göster)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void siparislerigöster(){
        String message="";
        int tutar=0;
        if(siparisler.isEmpty()){
            message="Siparişiniz bulunmamaktadır";
        }
        else{
            
            message+="SİPARİŞLER\n";
            
                for (Map.Entry<String, Integer> entry : siparisler.entrySet()) {
             
                    message+=entry.getKey()+"\n";
                    tutar+=entry.getValue();
                 
                }
                message+="Toplam tutar: "+tutar;   
        }
        
        JOptionPane.showMessageDialog(this,message);
        
        
    }
    
    private void gösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gösterActionPerformed
        if(iskender.isSelected()){
            siparisler.put("iskender", 15);
        }else{
            siparisler.remove("iskender");
        }
        
        if(Beyti.isSelected()){
            siparisler.put("Beyti", 20);
        }else{
            siparisler.remove("Beyti");
        }
        
        if(Döner.isSelected()){
            siparisler.put("Döner", 12);
        }else{
            siparisler.remove("Döner");
        }
        
        if(Ayran.isSelected()){
            siparisler.put("Ayran", 3);
        }else{
            siparisler.remove("Ayran");
        }
        
        siparislerigöster();
    }//GEN-LAST:event_gösterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparidUyg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparidUyg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparidUyg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparidUyg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparidUyg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ayran;
    private javax.swing.JCheckBox Beyti;
    private javax.swing.JCheckBox Döner;
    private javax.swing.JButton göster;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
